# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /nfs/zfs-student-6/users/ddu-toit/Sandbox/ft_retro

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /nfs/zfs-student-6/users/ddu-toit/Sandbox/ft_retro

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /nfs/zfs-student-6/users/ddu-toit/Sandbox/ft_retro/CMakeFiles /nfs/zfs-student-6/users/ddu-toit/Sandbox/ft_retro/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /nfs/zfs-student-6/users/ddu-toit/Sandbox/ft_retro/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ft_retro

# Build rule for target.
ft_retro: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ft_retro
.PHONY : ft_retro

# fast build rule for target.
ft_retro/fast:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/build
.PHONY : ft_retro/fast

Enemy.o: Enemy.cpp.o

.PHONY : Enemy.o

# target to build an object file
Enemy.cpp.o:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/Enemy.cpp.o
.PHONY : Enemy.cpp.o

Enemy.i: Enemy.cpp.i

.PHONY : Enemy.i

# target to preprocess a source file
Enemy.cpp.i:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/Enemy.cpp.i
.PHONY : Enemy.cpp.i

Enemy.s: Enemy.cpp.s

.PHONY : Enemy.s

# target to generate assembly for a file
Enemy.cpp.s:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/Enemy.cpp.s
.PHONY : Enemy.cpp.s

Entity.o: Entity.cpp.o

.PHONY : Entity.o

# target to build an object file
Entity.cpp.o:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/Entity.cpp.o
.PHONY : Entity.cpp.o

Entity.i: Entity.cpp.i

.PHONY : Entity.i

# target to preprocess a source file
Entity.cpp.i:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/Entity.cpp.i
.PHONY : Entity.cpp.i

Entity.s: Entity.cpp.s

.PHONY : Entity.s

# target to generate assembly for a file
Entity.cpp.s:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/Entity.cpp.s
.PHONY : Entity.cpp.s

EntityFactory.o: EntityFactory.cpp.o

.PHONY : EntityFactory.o

# target to build an object file
EntityFactory.cpp.o:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/EntityFactory.cpp.o
.PHONY : EntityFactory.cpp.o

EntityFactory.i: EntityFactory.cpp.i

.PHONY : EntityFactory.i

# target to preprocess a source file
EntityFactory.cpp.i:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/EntityFactory.cpp.i
.PHONY : EntityFactory.cpp.i

EntityFactory.s: EntityFactory.cpp.s

.PHONY : EntityFactory.s

# target to generate assembly for a file
EntityFactory.cpp.s:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/EntityFactory.cpp.s
.PHONY : EntityFactory.cpp.s

GameClock.o: GameClock.cpp.o

.PHONY : GameClock.o

# target to build an object file
GameClock.cpp.o:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/GameClock.cpp.o
.PHONY : GameClock.cpp.o

GameClock.i: GameClock.cpp.i

.PHONY : GameClock.i

# target to preprocess a source file
GameClock.cpp.i:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/GameClock.cpp.i
.PHONY : GameClock.cpp.i

GameClock.s: GameClock.cpp.s

.PHONY : GameClock.s

# target to generate assembly for a file
GameClock.cpp.s:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/GameClock.cpp.s
.PHONY : GameClock.cpp.s

GameManager.o: GameManager.cpp.o

.PHONY : GameManager.o

# target to build an object file
GameManager.cpp.o:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/GameManager.cpp.o
.PHONY : GameManager.cpp.o

GameManager.i: GameManager.cpp.i

.PHONY : GameManager.i

# target to preprocess a source file
GameManager.cpp.i:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/GameManager.cpp.i
.PHONY : GameManager.cpp.i

GameManager.s: GameManager.cpp.s

.PHONY : GameManager.s

# target to generate assembly for a file
GameManager.cpp.s:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/GameManager.cpp.s
.PHONY : GameManager.cpp.s

MapElement.o: MapElement.cpp.o

.PHONY : MapElement.o

# target to build an object file
MapElement.cpp.o:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/MapElement.cpp.o
.PHONY : MapElement.cpp.o

MapElement.i: MapElement.cpp.i

.PHONY : MapElement.i

# target to preprocess a source file
MapElement.cpp.i:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/MapElement.cpp.i
.PHONY : MapElement.cpp.i

MapElement.s: MapElement.cpp.s

.PHONY : MapElement.s

# target to generate assembly for a file
MapElement.cpp.s:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/MapElement.cpp.s
.PHONY : MapElement.cpp.s

MapObject.o: MapObject.cpp.o

.PHONY : MapObject.o

# target to build an object file
MapObject.cpp.o:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/MapObject.cpp.o
.PHONY : MapObject.cpp.o

MapObject.i: MapObject.cpp.i

.PHONY : MapObject.i

# target to preprocess a source file
MapObject.cpp.i:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/MapObject.cpp.i
.PHONY : MapObject.cpp.i

MapObject.s: MapObject.cpp.s

.PHONY : MapObject.s

# target to generate assembly for a file
MapObject.cpp.s:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/MapObject.cpp.s
.PHONY : MapObject.cpp.s

MovingEntity.o: MovingEntity.cpp.o

.PHONY : MovingEntity.o

# target to build an object file
MovingEntity.cpp.o:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/MovingEntity.cpp.o
.PHONY : MovingEntity.cpp.o

MovingEntity.i: MovingEntity.cpp.i

.PHONY : MovingEntity.i

# target to preprocess a source file
MovingEntity.cpp.i:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/MovingEntity.cpp.i
.PHONY : MovingEntity.cpp.i

MovingEntity.s: MovingEntity.cpp.s

.PHONY : MovingEntity.s

# target to generate assembly for a file
MovingEntity.cpp.s:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/MovingEntity.cpp.s
.PHONY : MovingEntity.cpp.s

Player.o: Player.cpp.o

.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i

.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s

.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/Player.cpp.s
.PHONY : Player.cpp.s

ShootingEntity.o: ShootingEntity.cpp.o

.PHONY : ShootingEntity.o

# target to build an object file
ShootingEntity.cpp.o:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/ShootingEntity.cpp.o
.PHONY : ShootingEntity.cpp.o

ShootingEntity.i: ShootingEntity.cpp.i

.PHONY : ShootingEntity.i

# target to preprocess a source file
ShootingEntity.cpp.i:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/ShootingEntity.cpp.i
.PHONY : ShootingEntity.cpp.i

ShootingEntity.s: ShootingEntity.cpp.s

.PHONY : ShootingEntity.s

# target to generate assembly for a file
ShootingEntity.cpp.s:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/ShootingEntity.cpp.s
.PHONY : ShootingEntity.cpp.s

Vector2.o: Vector2.cpp.o

.PHONY : Vector2.o

# target to build an object file
Vector2.cpp.o:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/Vector2.cpp.o
.PHONY : Vector2.cpp.o

Vector2.i: Vector2.cpp.i

.PHONY : Vector2.i

# target to preprocess a source file
Vector2.cpp.i:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/Vector2.cpp.i
.PHONY : Vector2.cpp.i

Vector2.s: Vector2.cpp.s

.PHONY : Vector2.s

# target to generate assembly for a file
Vector2.cpp.s:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/Vector2.cpp.s
.PHONY : Vector2.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ft_retro.dir/build.make CMakeFiles/ft_retro.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ft_retro"
	@echo "... Enemy.o"
	@echo "... Enemy.i"
	@echo "... Enemy.s"
	@echo "... Entity.o"
	@echo "... Entity.i"
	@echo "... Entity.s"
	@echo "... EntityFactory.o"
	@echo "... EntityFactory.i"
	@echo "... EntityFactory.s"
	@echo "... GameClock.o"
	@echo "... GameClock.i"
	@echo "... GameClock.s"
	@echo "... GameManager.o"
	@echo "... GameManager.i"
	@echo "... GameManager.s"
	@echo "... MapElement.o"
	@echo "... MapElement.i"
	@echo "... MapElement.s"
	@echo "... MapObject.o"
	@echo "... MapObject.i"
	@echo "... MapObject.s"
	@echo "... MovingEntity.o"
	@echo "... MovingEntity.i"
	@echo "... MovingEntity.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... ShootingEntity.o"
	@echo "... ShootingEntity.i"
	@echo "... ShootingEntity.s"
	@echo "... Vector2.o"
	@echo "... Vector2.i"
	@echo "... Vector2.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

